"""token refresh adicionado

Revision ID: 4dad6ca115ce
Revises: ea7a88df5712
Create Date: 2026-03-11 08:54:30.867933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4dad6ca115ce'
down_revision: Union[str, Sequence[str], None] = 'ea7a88df5712'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('token_refresh', sa.Text(), nullable=True))
    op.create_unique_constraint(None, 'usuario', ['token_refresh'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'usuario', type_='unique')
    op.drop_column('usuario', 'token_refresh')
    # ### end Alembic commands ###
